/**
 * Production: the backend lives on Railway, the app itself on Vercel.
 *
 * This domain was generated by Railway for the enrosed-erp-backend service;
 * it changes only if that service is recreated.
 */
export const environment = {
  apiBase: 'https://enrosed-erp-backend-production.up.railway.app',
  websitePreviewUrl: 'https://enrosed.com',
  environmentLabel: null,
};
